// categories.js
export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

// article.js
export const REQUEST_ARTICLES_BY_CATEGORIES = 'REQUEST_ARTICLES_BY_CATEGORIES';
export const RECEIVE_ARTICLES_BY_CATEGORIES = 'RECEIVE_ARTICLES_BY_CATEGORIES';
export const REQUEST_ARTICLE_CONTENT = 'REQUEST_ARTICLE_CONTENT';
export const RECEIVE_ARTICLE_CONTENT = 'RECEIVE_ARTICLE_CONTENT';
